name: Compare packages
on:
  pull_request

jobs:
  compare_packages:
    name: Compare packages to main
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v1
      - name: Run Comparison
        id: run_comparison
        shell: bash
        run: |
          git checkout main
          dotnet build
          dotnet list package --include-transitive > packages-before.txt

          git checkout -
          dotnet build
          dotnet list package --include-transitive > packages-after.txt

      - name: build package compare
        run: |
          ls
          dotnet run --project src/PackageLister.Console ./packages-before.md ./packages-after.md 

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        # if: ${{ env.DIFF_OUTPUT }}
        with:
          message: |
            Hello world ! :wave:
            ${{ env.JSON_RESPONSE }}
            ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}
