name: Compare packages
on:
  pull_request

jobs:
  compare_packages:
    name: Compare packages to main
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v1
      - name: Run Comparison
        id: run_comparison
        shell: bash
        run: |
          git checkout main
          dotnet build
          dotnet list package --include-transitive > packages-before.txt

          git checkout -
          dotnet build
          dotnet list package --include-transitive > packages-after.txt

          diff packages-before.txt packages-after.txt || true

          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "DIFF<<$EOF" >> $GITHUB_ENV
          diff packages-before.txt packages-after.txt || true >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        if: ${{ env.action_state }}
        with:
          message: |
            Hello world ! :wave:
            "${{ env.DIFF }}"
