name: Compare packages
on:
  pull_request

jobs:
  compare_packages:
    name: Compare packages to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          path: repo
      - name: Run Comparison
        shell: bash
        run: |
          ls
          git init
          cd repo
          dotnet list package --include-transitive > ../packages

          cd ../
          git add .
          git commit -m "initial"

          cd repo
          git checkout -
          dotnet list package --include-transitive > ../packages
          cd ../
          git diff

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world ! :wave: