name: Compare packages
on:
  pull_request

jobs:
  compare_packages:
    name: Compare packages to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Comparison
        shell: bash
        run: |
          git checkout main
          dotnet build
          dotnet list package --include-transitive > packages-before.txt

          cd repo
          git checkout -
          dotnet build
          dotnet list package --include-transitive > packages-after.txt

          diff packages-before.txt packages-after.txt
          echo ok
          diff=$(diff packages-before.txt packages-after.txt)
          echo $diff
          echo "::set-output name=diff::$diff"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world ! :wave: