name: Compare packages
on:
  pull_request

jobs:
  compare_packages:
    name: Compare packages to main
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v1
      - name: Run Comparison
        id: run_comparison
        shell: bash
        run: |
          git checkout main
          dotnet build
          dotnet list package --include-transitive > packages.txt

          git checkout -
          git add .
          git commit -m "before"

          dotnet build
          dotnet list package --include-transitive > packages.txt

          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "DIFF_OUTPUT<<$EOF" >> $GITHUB_ENV
          git diff >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        # if: ${{ env.DIFF_OUTPUT }}
        with:
          message: |
            Hello world ! :wave:
            ${{ env.DIFF_OUTPUT }}
