name: Run format

on:
  push

jobs:
  run-format:
    name: Run Format
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1

    - name: Format
      run: dotnet format --verify-no-changes
